#pragma once

#include "grid.h"
#include "types.h"

#include <cstdint>
#include <vector>

// Track lifecycle (contract §8).
enum class TrackStatus { FRESH, STALE, EXPIRED };

// Per-scenario track tuning. All rates are per-round.
struct BeliefConfig {
    int fresh_rounds = 2;              // rounds a track stays FRESH after last update
    int stale_rounds = 4;              // additional rounds before EXPIRED
    float uncertainty_growth_per_round = 1.0f; // cells
    float confidence_decay_per_round = 0.15f;
};

// A tracked believed enemy position (contract §8).
struct Track {
    EntityId target = 0;
    GridPos estimated_position{};
    float confidence = 0.0f;
    float uncertainty = 0.0f;         // cells
    int last_update_round = 0;
    int last_decay_round = 0;
    TrackStatus status = TrackStatus::FRESH;

    int class_id = 0;                 // believed unit type (0 = unknown)
    uint32_t source_mask = 0;         // bitmask of contributing sources
};

// A single sighting event. Sightings are the input to belief updates.
// Generated by: direct LOS contact during activation, drone feed during
// support phase, camera feed, or a spoof injection.
struct Sighting {
    EntityId observer = 0;            // the sensing unit (or device), 0 = spoof/synthetic
    EntityId target = 0;
    GridPos estimated_position{};
    float confidence = 1.0f;
    float uncertainty = 0.0f;
    int class_id = 0;
    bool is_spoof = false;            // synthetic injection
};

struct BeliefState {
    std::vector<Track> tracks;

    // Create or refresh a track from a sighting.
    void update(const Sighting& s, int current_round);

    // Age all tracks: grow uncertainty, decay confidence, transition status,
    // remove expired tracks. Called once per round (contract Phase 1).
    void decay(int current_round, const BeliefConfig& config);

    Track* find_track(EntityId target);
    const Track* find_track(EntityId target) const;

    // Remove all spoofed tracks in the given area (contract §5 drone scan).
    void clear_spoofs_in(GridPos center, int radius);
};

const char* track_status_str(TrackStatus s);
